/**
 * Nomes em português dos tipos de evento (EVENT_TYPES) e dos domínios, para os seletores de gatilho do
 * construtor de processos e do editor de automações e para os resumos de automações. Fonte única: não
 * mostre a chave técnica ("lead.created") como rótulo principal.
 */
import { EVENT_TYPES, type EventType } from "./constants";

export const EVENT_TYPE_LABELS: Record<EventType, string> = {
  "client.created": "Cliente cadastrado",
  "client.updated": "Cliente atualizado",
  "client.status_changed": "Status do cliente alterado",
  "contact.created": "Contato cadastrado",
  "task.created": "Tarefa criada",
  "task.updated": "Tarefa atualizada",
  "task.status_changed": "Status da tarefa alterado",
  "task.completed": "Tarefa concluída",
  "task.assigned": "Tarefa atribuída",
  "comment.added": "Comentário adicionado",
  "document.added": "Documento anexado",
  "note.added": "Nota registrada",
  "workflow.started": "Jornada iniciada",
  "workflow.stage.started": "Etapa da jornada iniciada",
  "workflow.stage.completed": "Etapa da jornada concluída",
  "workflow.stage.blocked": "Etapa da jornada bloqueada",
  "workflow.completed": "Jornada concluída",
  "workflow.gate.rejected": "Gate da etapa recusado",
  "sla.started": "SLA iniciado",
  "sla.at_risk": "SLA em risco",
  "sla.breached": "SLA violado",
  "sla.paused": "SLA pausado",
  "sla.resumed": "SLA retomado",
  "sla.completed": "SLA concluído",
  "notification.sent": "Notificação enviada",
  "user.created": "Usuário criado",
  "user.updated": "Usuário atualizado",
  "lead.created": "Lead criado",
  "lead.updated": "Lead atualizado",
  "lead.qualified": "Lead qualificado",
  "lead.disqualified": "Lead desqualificado",
  "lead.contacted": "Lead contatado",
  "prospect.contacted": "Contato da prospecção ativa",
  "opportunity.created": "Oportunidade criada",
  "opportunity.stage_changed": "Etapa da oportunidade alterada",
  "opportunity.followup_scheduled": "Follow-up agendado",
  "opportunity.followup_overdue": "Follow-up vencido",
  "opportunity.stalled": "Oportunidade parada",
  "opportunity.won": "Negócio ganho",
  "opportunity.lost": "Negócio perdido",
  "proposal.created": "Proposta criada",
  "proposal.sent": "Proposta enviada",
  "proposal.viewed": "Proposta visualizada",
  "proposal.accepted": "Proposta aceita",
  "proposal.rejected": "Proposta recusada",
  "visit.scheduled": "Visita agendada",
  "visit.completed": "Visita realizada",
  "whatsapp.message.received": "WhatsApp recebido",
  "whatsapp.message.sent": "WhatsApp enviado/registrado",
  "call.completed": "Ligação registrada",
  "contract.created": "Contrato criado",
  "contract.sent_for_signature": "Documento enviado para assinatura",
  "contract.signed": "Contrato assinado",
  "contract.version_created": "Nova versão do contrato",
  "billing.created": "Cobrança gerada",
  "payment.pending": "Pagamento pendente",
  "payment.approved": "Pagamento aprovado",
  "payment.overdue": "Cobrança vencida",
  "financial.released": "Liberação financeira",
  "implementation.created": "Implantação criada",
  "implementation.started": "Implantação iniciada",
  "implementation.task.completed": "Tarefa da implantação concluída",
  "implementation.waiting_client": "Implantação aguardando o cliente",
  "implementation.resumed": "Implantação retomada",
  "implementation.training.completed": "Treinamento realizado",
  "implementation.go_live": "Go-live aprovado",
  "customer.activated": "Cliente ativado",
  "customer.health_changed": "Saúde do cliente alterada",
  "customer.risk.detected": "Risco de cliente detectado",
  "customer.checkpoint.completed": "Checkpoint de CS registrado",
  "success_plan.created": "Plano de sucesso criado",
  "renewal.due": "Renovação próxima",
  "renewal.completed": "Renovação concluída",
  "churn.registered": "Cancelamento registrado",
  "upsell.created": "Upsell criado",
  "support.ticket.created": "Chamado aberto",
  "support.ticket.first_response": "Primeira resposta do chamado",
  "support.ticket.status_changed": "Status do chamado alterado",
  "support.ticket.resolved": "Chamado resolvido",
  "support.ticket.reopened": "Chamado reaberto",
  "support.csat.received": "Avaliação (CSAT) recebida",
  "kpi.updated": "Indicador atualizado",
  "goal.achieved": "Meta atingida",
  "commission.calculated": "Comissão calculada",
  "bonus.calculated": "Bônus calculado",
  "bonus.blocked": "Bônus bloqueado",
  "gamification.points_awarded": "Pontos de gamificação creditados",
  "achievement.unlocked": "Conquista desbloqueada",
  "automation.executed": "Automação executada",
  "goal.created": "Meta criada",
  "goal.updated": "Meta atualizada",
  "bonus.block_registered": "Bloqueio de bônus registrado",
  "bonus.block_revoked": "Bloqueio de bônus revogado",
  "campaign.progress": "Progresso de campanha",
  "report.exported": "Relatório exportado",
  "automation.rule_updated": "Regra de automação alterada",
  "insight.detected": "Insight detectado",
  "ai.suggestion_generated": "Sugestão da IA gerada",
  "workflow.step.updated": "Etapa da jornada atualizada",
  "workflow.step.reassigned": "Etapa da jornada reatribuída",
  "workflow.template.published": "Processo publicado",
  "implementation.phase_changed": "Fase da implantação alterada",
  "implementation.updated": "Implantação atualizada",
  "support.ticket.reclassified": "Chamado reclassificado",
  "success_plan.updated": "Plano de sucesso atualizado",
  "customer.escalated": "Cliente escalonado",
  "campaign.updated": "Campanha atualizada",
  "prospect_list.updated": "Lista de prospecção atualizada",
  "visit.cancelled": "Visita cancelada",
  "commission.released": "Comissão liberada",
  "contract.updated": "Contrato atualizado",
  "billing.cancelled": "Cobrança cancelada",
  "user.deleted": "Usuário removido",
  "department.updated": "Departamento atualizado",
  "product.updated": "Produto atualizado",
  "support.ticket.transferred": "Chamado transferido",
  "knowledge.article.created": "Artigo da base criado",
  "knowledge.article.voted": "Avaliação de artigo da base",
  "opportunity.reassigned": "Oportunidade transferida",
  "email.sent": "E-mail enviado/registrado",
  "settings.updated": "Configuração alterada",
};

const DOMAIN_LABELS: Record<string, string> = {
  client: "Clientes",
  contact: "Clientes",
  customer: "Customer Success",
  success_plan: "Customer Success",
  renewal: "Customer Success",
  churn: "Customer Success",
  upsell: "Customer Success",
  task: "Tarefas",
  comment: "Tarefas",
  document: "Documentos e notas",
  note: "Documentos e notas",
  workflow: "Jornada e processos",
  sla: "SLA",
  notification: "Sistema",
  user: "Sistema",
  department: "Sistema",
  product: "Sistema",
  settings: "Sistema",
  report: "Sistema",
  insight: "Sistema",
  ai: "Sistema",
  automation: "Sistema",
  lead: "Marketing",
  prospect: "Marketing",
  prospect_list: "Marketing",
  campaign: "Marketing e campanhas",
  opportunity: "Vendas",
  proposal: "Vendas",
  visit: "Vendas",
  whatsapp: "Comunicação",
  call: "Comunicação",
  email: "Comunicação",
  contract: "Financeiro",
  billing: "Financeiro",
  payment: "Financeiro",
  financial: "Financeiro",
  implementation: "Implantação",
  support: "Suporte",
  knowledge: "Suporte",
  kpi: "Performance",
  goal: "Performance",
  commission: "Performance",
  bonus: "Performance",
  gamification: "Performance",
  achievement: "Performance",
};

export function eventTypeLabel(type: string): string {
  return EVENT_TYPE_LABELS[type as EventType] ?? type;
}

/** Tipos de evento agrupados por área, com rótulos em português (ordem dos grupos: primeira ocorrência). */
export function eventTypeGroups(types: readonly EventType[] = EVENT_TYPES): { label: string; types: { value: EventType; label: string }[] }[] {
  const groups = new Map<string, { value: EventType; label: string }[]>();
  for (const t of types) {
    const label = DOMAIN_LABELS[t.split(".")[0]] ?? "Outros";
    groups.set(label, [...(groups.get(label) ?? []), { value: t, label: EVENT_TYPE_LABELS[t] }]);
  }
  return Array.from(groups, ([label, items]) => ({ label, types: items }));
}
