import {
  Activity,
  AlertTriangle,
  Award,
  BarChart3,
  Bell,
  BookOpen,
  Briefcase,
  Building2,
  Calendar,
  CalendarCheck,
  CheckSquare,
  Circle,
  Crosshair,
  FileSignature,
  FileText,
  Flag,
  Gauge,
  GitBranch,
  Goal,
  GraduationCap,
  Handshake,
  Headset,
  HeartPulse,
  Inbox,
  Kanban,
  LayoutDashboard,
  ListChecks,
  MapPin,
  Megaphone,
  Menu,
  Network,
  Package,
  PenLine,
  Radar,
  Receipt,
  RefreshCw,
  Repeat,
  Rocket,
  Route,
  Settings,
  Sparkles,
  Sun,
  Target,
  Ticket,
  Timer,
  TrendingUp,
  Trophy,
  UserPlus,
  Users,
  Wallet,
  Workflow,
  type LucideIcon,
  type LucideProps,
} from "lucide-react";

/** Mapa explícito nome -> ícone lucide. Cobre todos os nomes usados em NAVIGATION e MOBILE_NAV. */
export const NAV_ICONS: Record<string, LucideIcon> = {
  Sun,
  Bell,
  CheckSquare,
  GitBranch,
  Building2,
  Megaphone,
  UserPlus,
  Flag,
  Inbox,
  Crosshair,
  Handshake,
  Kanban,
  Target,
  Calendar,
  MapPin,
  FileText,
  FileSignature,
  PenLine,
  Receipt,
  Wallet,
  Repeat,
  Rocket,
  ListChecks,
  GraduationCap,
  Briefcase,
  HeartPulse,
  CalendarCheck,
  Route,
  RefreshCw,
  AlertTriangle,
  TrendingUp,
  Headset,
  Ticket,
  Timer,
  BookOpen,
  Gauge,
  Goal,
  Award,
  Trophy,
  Sparkles,
  LayoutDashboard,
  Radar,
  BarChart3,
  Users,
  Network,
  Package,
  Settings,
  Workflow,
  Activity,
  Menu,
};

export interface NavIconProps extends LucideProps {
  name: string;
}

/** Renderiza o ícone pelo nome (string de NavItem.icon). Nome desconhecido cai em um círculo. */
export function NavIcon({ name, ...props }: NavIconProps) {
  const Icon = NAV_ICONS[name] ?? Circle;
  return <Icon aria-hidden {...props} />;
}
