/**
 * Definições de processo de demonstração, gravadas por scripts/seed/catalog.ts com IDs determinísticos.
 * Sem dependências de servidor: pode ser importado pelo seed.
 *
 * - "Implantação de novos clientes" v3 em RASCUNHO: reproduz o fluxo da referência sem disparar (o projeto de
 *   implantação real continua sendo criado pelo Financeiro na liberação do contrato).
 * - "Cobrança de inadimplente" PUBLICADO, gatilho payment.overdue.
 * - "Onboarding CS 30 dias" PUBLICADO, gatilho customer.activated.
 */
import type { ProcessDefinition } from "@/domain/workflow-graph";

export type SeedProcessDefinition = Omit<ProcessDefinition, "organizationId" | "createdAt" | "updatedAt">;

export const PROCESS_SEED_DEFINITIONS: SeedProcessDefinition[] = [
  {
    id: "pdef_implantacao_novos_clientes_v3",
    key: "implantacao-novos-clientes",
    name: "Implantação de novos clientes",
    description: "Do contrato assinado ao go-live: pagamento, kickoff, configuração, treinamento e homologação.",
    version: 3,
    status: "rascunho",
    trigger: { type: "evento", eventType: "contract.signed" },
    nodes: [
      { id: "inicio", type: "inicio", position: { x: 0, y: 2 }, data: { label: "Novo contrato assinado" } },
      {
        id: "validar_pagamento",
        type: "tarefa",
        position: { x: 200, y: 0 },
        data: {
          label: "Validar pagamento",
          department: "financeiro",
          assignee: "papel:financeiro",
          priority: "alta",
          dueBusinessDays: 1,
          slaHours: 8,
          requiredFields: ["Comprovante de pagamento conferido"],
          checklist: ["Condição de pagamento conferida com o contrato"],
          autoCreateTask: true,
          notify: true,
          outcome: "sim_nao",
          outcomeQuestion: "Pagamento aprovado?",
        },
      },
      { id: "pagamento_aprovado", type: "condicao", position: { x: 420, y: -34 }, data: { label: "Pagamento aprovado?", mode: "resultado", fromNode: "validar_pagamento" } },
      {
        id: "alertar_financeiro",
        type: "notificacao",
        position: { x: 610, y: 0 },
        data: {
          label: "Alertar Financeiro",
          to: "gestor_departamento",
          department: "financeiro",
          kind: "atencao",
          title: "Pagamento não aprovado: {{client.tradeName}}",
          body: "A implantação aguarda a validação do pagamento.",
        },
      },
      {
        id: "agendar_kickoff",
        type: "tarefa",
        position: { x: 396, y: 150 },
        data: {
          label: "Agendar kickoff",
          department: "implantacao",
          assignee: "responsavel_cliente:ownerImplementationId",
          priority: "alta",
          dueBusinessDays: 2,
          slaHours: 16,
          requiredFields: [],
          checklist: ["Participantes do cliente confirmados", "Pauta enviada"],
          autoCreateTask: true,
          notify: true,
        },
      },
      {
        id: "configuracao_sistema",
        type: "tarefa",
        position: { x: 396, y: 260 },
        data: {
          label: "Configuração do sistema",
          department: "implantacao",
          assignee: "responsavel_cliente:ownerImplementationId",
          priority: "media",
          dueBusinessDays: 2,
          slaHours: 16,
          requiredFields: ["Ambiente configurado", "Acessos e permissões definidos", "Integrações validadas", "Documentação entregue"],
          checklist: [],
          autoCreateTask: true,
          notify: true,
        },
      },
      {
        id: "treinamento_cliente",
        type: "tarefa",
        position: { x: 396, y: 370 },
        data: {
          label: "Treinamento do cliente",
          department: "implantacao",
          assignee: "responsavel_cliente:ownerImplementationId",
          priority: "media",
          dueBusinessDays: 3,
          slaHours: 24,
          requiredFields: ["Treinamento realizado"],
          checklist: ["Material enviado ao cliente"],
          autoCreateTask: true,
          notify: true,
          outcome: "sim_nao",
          outcomeQuestion: "Cliente homologou?",
        },
      },
      { id: "cliente_homologou", type: "condicao", position: { x: 420, y: 470 }, data: { label: "Cliente homologou?", mode: "resultado", fromNode: "treinamento_cliente" } },
      { id: "go_live", type: "fim", position: { x: 404, y: 650 }, data: { label: "Go-live concluído" } },
    ],
    edges: [
      { id: "e1", source: "inicio", target: "validar_pagamento", sourceHandle: "r", targetHandle: "l" },
      { id: "e2", source: "validar_pagamento", target: "pagamento_aprovado", sourceHandle: "r", targetHandle: "l" },
      { id: "e3", source: "pagamento_aprovado", target: "agendar_kickoff", label: "sim", sourceHandle: "sim", targetHandle: "t" },
      { id: "e4", source: "pagamento_aprovado", target: "alertar_financeiro", label: "nao", sourceHandle: "nao", targetHandle: "l" },
      { id: "e5", source: "alertar_financeiro", target: "validar_pagamento", sourceHandle: "b", targetHandle: "tb" },
      { id: "e6", source: "agendar_kickoff", target: "configuracao_sistema" },
      { id: "e7", source: "configuracao_sistema", target: "treinamento_cliente" },
      { id: "e8", source: "treinamento_cliente", target: "cliente_homologou" },
      { id: "e9", source: "cliente_homologou", target: "go_live", label: "sim", sourceHandle: "sim", targetHandle: "t" },
      { id: "e10", source: "cliente_homologou", target: "treinamento_cliente", label: "nao", sourceHandle: "nao", targetHandle: "tr" },
    ],
  },
  {
    id: "pdef_cobranca_inadimplente_v1",
    key: "cobranca-inadimplente",
    name: "Cobrança de inadimplente",
    description: "Cobrança vencida: contato do Financeiro, espera de 3 dias úteis e escalonamento ao gestor se seguir em aberto.",
    version: 1,
    status: "publicado",
    trigger: { type: "evento", eventType: "payment.overdue" },
    publishedBy: "user_hercules",
    nodes: [
      { id: "inicio", type: "inicio", position: { x: 0, y: 0 }, data: { label: "Cobrança vencida" } },
      {
        id: "contato_cobranca",
        type: "tarefa",
        position: { x: -20, y: 130 },
        data: {
          label: "Contato de cobrança com o cliente",
          department: "financeiro",
          assignee: "papel:financeiro",
          priority: "alta",
          dueBusinessDays: 1,
          slaHours: 8,
          requiredFields: ["Cliente contatado"],
          checklist: ["Promessa de pagamento registrada"],
          autoCreateTask: true,
          notify: true,
        },
      },
      { id: "aguardar_3_dias", type: "espera", position: { x: -20, y: 260 }, data: { label: "Aguardar 3 dias úteis", mode: "horas_uteis", businessHours: 30 } },
      { id: "cobranca_paga", type: "condicao", position: { x: 5, y: 380 }, data: { label: "Cobrança paga?", mode: "contexto", path: "entity.status", operator: "==", value: "paga" } },
      { id: "fim_regularizada", type: "fim", position: { x: -260, y: 560 }, data: { label: "Cobrança regularizada" } },
      {
        id: "avisar_gestor",
        type: "notificacao",
        position: { x: 260, y: 400 },
        data: {
          label: "Avisar gestor financeiro",
          to: "gestor_departamento",
          department: "financeiro",
          kind: "atencao",
          title: "Inadimplência sem regularização: {{client.tradeName}}",
          body: "A cobrança segue em aberto após 3 dias úteis do contato. Uma ligação de cobrança foi aberta.",
        },
      },
      {
        id: "ligacao_cobranca",
        type: "tarefa",
        position: { x: 260, y: 540 },
        data: {
          label: "Ligação de cobrança",
          department: "financeiro",
          assignee: "papel:financeiro",
          priority: "alta",
          dueBusinessDays: 1,
          slaHours: 8,
          requiredFields: [],
          checklist: ["Negociar data de pagamento", "Registrar resultado da ligação"],
          autoCreateTask: true,
          notify: true,
        },
      },
      { id: "fim_negociacao", type: "fim", position: { x: 260, y: 680 }, data: { label: "Encaminhado para negociação" } },
    ],
    edges: [
      { id: "e1", source: "inicio", target: "contato_cobranca" },
      { id: "e2", source: "contato_cobranca", target: "aguardar_3_dias" },
      { id: "e3", source: "aguardar_3_dias", target: "cobranca_paga" },
      { id: "e4", source: "cobranca_paga", target: "fim_regularizada", label: "sim", sourceHandle: "sim", targetHandle: "t" },
      { id: "e5", source: "cobranca_paga", target: "avisar_gestor", label: "nao", sourceHandle: "nao", targetHandle: "l" },
      { id: "e6", source: "avisar_gestor", target: "ligacao_cobranca" },
      { id: "e7", source: "ligacao_cobranca", target: "fim_negociacao" },
    ],
  },
  {
    id: "pdef_onboarding_cs_30_dias_v1",
    key: "onboarding-cs-30-dias",
    name: "Onboarding CS 30 dias",
    description: "Após a ativação: checkpoints de D+7, D+15 e D+30 com o responsável de CS do cliente.",
    version: 1,
    status: "publicado",
    trigger: { type: "evento", eventType: "customer.activated" },
    publishedBy: "user_hercules",
    nodes: [
      { id: "inicio", type: "inicio", position: { x: 0, y: 0 }, data: { label: "Cliente ativado" } },
      { id: "aguardar_d7", type: "espera", position: { x: -20, y: 120 }, data: { label: "Aguardar até D+7", mode: "horas_uteis", businessHours: 50 } },
      {
        id: "checkpoint_d7",
        type: "tarefa",
        position: { x: -20, y: 240 },
        data: {
          label: "Checkpoint D+7",
          department: "cs",
          assignee: "responsavel_cliente:ownerCsId",
          priority: "media",
          dueBusinessDays: 2,
          slaHours: 16,
          requiredFields: ["Contato realizado"],
          checklist: ["Uso das funções principais", "Dúvidas do time do cliente", "Próximos passos combinados"],
          autoCreateTask: true,
          notify: true,
        },
      },
      { id: "aguardar_d15", type: "espera", position: { x: -20, y: 360 }, data: { label: "Aguardar até D+15", mode: "horas_uteis", businessHours: 60 } },
      {
        id: "checkpoint_d15",
        type: "tarefa",
        position: { x: -20, y: 480 },
        data: {
          label: "Checkpoint D+15",
          department: "cs",
          assignee: "responsavel_cliente:ownerCsId",
          priority: "media",
          dueBusinessDays: 2,
          slaHours: 16,
          requiredFields: ["Contato realizado"],
          checklist: ["Adoção por usuário revisada", "Chamados abertos revisados"],
          autoCreateTask: true,
          notify: true,
        },
      },
      { id: "aguardar_d30", type: "espera", position: { x: -20, y: 600 }, data: { label: "Aguardar até D+30", mode: "horas_uteis", businessHours: 110 } },
      {
        id: "checkpoint_d30",
        type: "tarefa",
        position: { x: -20, y: 720 },
        data: {
          label: "Checkpoint D+30",
          department: "cs",
          assignee: "responsavel_cliente:ownerCsId",
          priority: "alta",
          dueBusinessDays: 2,
          slaHours: 16,
          requiredFields: ["Contato realizado", "Saúde do cliente revisada"],
          checklist: ["Plano de sucesso atualizado", "Oportunidades de expansão registradas"],
          autoCreateTask: true,
          notify: true,
        },
      },
      { id: "fim", type: "fim", position: { x: -20, y: 850 }, data: { label: "Onboarding concluído" } },
    ],
    edges: [
      { id: "e1", source: "inicio", target: "aguardar_d7" },
      { id: "e2", source: "aguardar_d7", target: "checkpoint_d7" },
      { id: "e3", source: "checkpoint_d7", target: "aguardar_d15" },
      { id: "e4", source: "aguardar_d15", target: "checkpoint_d15" },
      { id: "e5", source: "checkpoint_d15", target: "aguardar_d30" },
      { id: "e6", source: "aguardar_d30", target: "checkpoint_d30" },
      { id: "e7", source: "checkpoint_d30", target: "fim" },
    ],
  },
];
